/**
 * Productos CRUD Page - Example Template
 * 
 * This is a self-contained CRUD module for the Productos resource.
 * Copy this file and adapt it for other resources following the same structure.
 * 
 * Key sections:
 * 1. Imports and configuration
 * 2. State management
 * 3. Data loading
 * 4. CRUD operations (Create, Update, Delete)
 * 5. UI rendering (table, form modal)
 * 6. Event handlers
 * 7. Initialization
 */

import { API_BASE_URL, getAuthHeaders, listResource, createResource, updateResource, deleteResource } from '../api.js';
import { showMessage, showConfirm } from '../utils.js';
import { checkPermission } from './core.js';

// ============================================================================
// CONFIGURATION
// ============================================================================

const RESOURCE_NAME = 'productos';
const DISPLAY_NAME = 'Productos';

const FIELDS = [
    { name: 'nombre', label: 'Nombre', type: 'text', required: true },
    { name: 'codigo', label: 'Código', type: 'text', required: false, autoGenerated: true }
];

// ============================================================================
// STATE
// ============================================================================

let currentData = [];
let currentPage = 1;
let totalPages = 1;
let editingId = null;

// ============================================================================
// DATA LOADING
// ============================================================================

async function loadData(page = 1) {
    try {
        const response = await listResource(RESOURCE_NAME, page, 50);
        currentData = response.items;
        currentPage = response.page;
        totalPages = response.pages;
        renderTable();
        renderPagination();
    } catch (error) {
        showMessage(`Error al cargar ${DISPLAY_NAME}: ${error.message}`, 'error');
    }
}

// ============================================================================
// CRUD OPERATIONS
// ============================================================================

async function handleCreate(formData) {
    try {
        // Remove auto-generated fields from form data
        const data = { ...formData };
        FIELDS.filter(f => f.autoGenerated).forEach(f => delete data[f.name]);
        
        await createResource(RESOURCE_NAME, data);
        showMessage(`${DISPLAY_NAME} creado exitosamente`, 'success');
        closeModal();
        loadData(currentPage);
    } catch (error) {
        showMessage(`Error al crear: ${error.message}`, 'error');
    }
}

async function handleUpdate(id, formData) {
    try {
        // Check permissions
        const permissions = checkPermission(RESOURCE_NAME);
        if (permissions.requiresAdminForEdit && !permissions.canEdit) {
            // This would trigger admin validation modal in full implementation
            showMessage('Requiere permisos de administrador', 'error');
            return;
        }
        
        await updateResource(RESOURCE_NAME, id, formData);
        showMessage(`${DISPLAY_NAME} actualizado exitosamente`, 'success');
        closeModal();
        loadData(currentPage);
    } catch (error) {
        showMessage(`Error al actualizar: ${error.message}`, 'error');
    }
}

async function handleDelete(id) {
    const confirmed = await showConfirm('¿Está seguro de eliminar este registro?');
    if (!confirmed) return;
    
    try {
        await deleteResource(RESOURCE_NAME, id);
        showMessage(`${DISPLAY_NAME} eliminado exitosamente`, 'success');
        loadData(currentPage);
    } catch (error) {
        showMessage(`Error al eliminar: ${error.message}`, 'error');
    }
}

// ============================================================================
// UI RENDERING
// ============================================================================

function renderTable() {
    const tbody = document.querySelector('#productosTable tbody');
    if (!tbody) return;
    
    tbody.innerHTML = '';
    
    currentData.forEach(item => {
        const tr = document.createElement('tr');
        tr.innerHTML = `
            <td>${item.id}</td>
            <td>${item.nombre}</td>
            <td>${item.codigo || 'N/A'}</td>
            <td>
                <button class="btn-edit" data-id="${item.id}">Editar</button>
                <button class="btn-delete" data-id="${item.id}">Eliminar</button>
            </td>
        `;
        tbody.appendChild(tr);
    });
    
    // Attach event listeners
    document.querySelectorAll('.btn-edit').forEach(btn => {
        btn.addEventListener('click', () => openEditModal(btn.dataset.id));
    });
    document.querySelectorAll('.btn-delete').forEach(btn => {
        btn.addEventListener('click', () => handleDelete(btn.dataset.id));
    });
}

function renderPagination() {
    const container = document.querySelector('#pagination');
    if (!container) return;
    
    container.innerHTML = '';
    
    for (let i = 1; i <= totalPages; i++) {
        const btn = document.createElement('button');
        btn.textContent = i;
        btn.className = i === currentPage ? 'active' : '';
        btn.addEventListener('click', () => loadData(i));
        container.appendChild(btn);
    }
}

function openCreateModal() {
    editingId = null;
    renderForm({});
    document.querySelector('#crudModal').classList.add('show');
}

function openEditModal(id) {
    editingId = id;
    const item = currentData.find(d => d.id === parseInt(id));
    if (item) {
        renderForm(item);
        document.querySelector('#crudModal').classList.add('show');
    }
}

function closeModal() {
    editingId = null;
    document.querySelector('#crudModal').classList.remove('show');
}

function renderForm(data = {}) {
    const form = document.querySelector('#crudForm');
    if (!form) return;
    
    form.innerHTML = '';
    
    FIELDS.forEach(field => {
        if (field.autoGenerated && !editingId) {
            // Skip auto-generated fields in create mode
            return;
        }
        
        const div = document.createElement('div');
        div.className = 'form-group';
        
        const label = document.createElement('label');
        label.textContent = field.label + (field.required ? ' *' : '');
        
        const input = document.createElement('input');
        input.type = field.type;
        input.name = field.name;
        input.value = data[field.name] || '';
        input.required = field.required;
        
        if (field.autoGenerated) {
            input.disabled = true;
        }
        
        div.appendChild(label);
        div.appendChild(input);
        form.appendChild(div);
    });
    
    // Submit button
    const submitBtn = document.createElement('button');
    submitBtn.type = 'submit';
    submitBtn.textContent = editingId ? 'Actualizar' : 'Crear';
    submitBtn.className = 'btn-primary';
    form.appendChild(submitBtn);
    
    // Cancel button
    const cancelBtn = document.createElement('button');
    cancelBtn.type = 'button';
    cancelBtn.textContent = 'Cancelar';
    cancelBtn.className = 'btn-secondary';
    cancelBtn.addEventListener('click', closeModal);
    form.appendChild(cancelBtn);
}

// ============================================================================
// EVENT HANDLERS
// ============================================================================

function handleFormSubmit(e) {
    e.preventDefault();
    
    const formData = new FormData(e.target);
    const data = Object.fromEntries(formData.entries());
    
    if (editingId) {
        handleUpdate(editingId, data);
    } else {
        handleCreate(data);
    }
}

// ============================================================================
// INITIALIZATION
// ============================================================================

export function ProductosInterface() {
    const container = document.createElement('div');
    container.className = 'crud-container';
    container.innerHTML = `
        <div class="crud-header">
            <h2>${DISPLAY_NAME}</h2>
            <button id="btnNew" class="btn-primary">Nueva Entrada</button>
        </div>
        
        <table id="productosTable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Código</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        
        <div id="pagination"></div>
        
        <div id="crudModal" class="modal">
            <div class="modal-content">
                <h3>${editingId ? 'Editar' : 'Nuevo'} ${DISPLAY_NAME}</h3>
                <form id="crudForm"></form>
            </div>
        </div>
    `;
    
    // Setup event listeners after DOM is ready
    setTimeout(() => {
        const btnNew = document.querySelector('#btnNew');
        if (btnNew) {
            btnNew.addEventListener('click', openCreateModal);
        }
        
        const form = document.querySelector('#crudForm');
        if (form) {
            form.addEventListener('submit', handleFormSubmit);
        }
        
        // Check permissions and hide/show buttons
        const permissions = checkPermission(RESOURCE_NAME);
        if (btnNew && !permissions.canCreate) {
            btnNew.style.display = 'none';
        }
        
        // Load initial data
        loadData(1);
    }, 0);
    
    return container;
}
