export const resourceConfigs = {
  usuarios: {
    title: "Gestión de Usuarios",
    resource: "combined/usuarios",
    fields: [
      { name: "usuario", label: "Usuario" },
      {
        name: "contrasena",
        label: "Contraseña",
        type: "password",
      },
      { name: "persona.nombre", label: "Nombre" },
      { name: "persona.apellido", label: "Apellido" },
      { name: "persona.cedula", label: "Cédula" },
      { name: "persona.direccion.pais", label: "País", defaultValue: "Venezuela" },
      { name: "persona.direccion.estado", label: "Estado" },
      { name: "persona.direccion.municipio", label: "Municipio" },
      { name: "persona.direccion.sector", label: "Sector" },
      { name: "persona.direccion.descripcion", label: "Dirección" },
      { name: "id_roles", label: "Rol" },
      { name: "created_at", label: "Fecha", readOnly: true },
    ],
  },
  roles: {
    title: "Gestión de Roles",
    resource: "roles",
    fields: [
      { name: "nombre", label: "Nombre del Rol" },
      { name: "created_at", label: "Fecha", readOnly: true },
    ],
  },
  productos: {
    title: "Gestión de Productos",
    resource: "productos",
    fields: [
      { name: "nombre", label: "Nombre" },
      { name: "created_at", label: "Fecha", readOnly: true },
    ],
  },
  empresas_transporte: {
    title: "Empresas de Transporte",
    resource: "combined/empresas_transporte",
    fields: [
      { name: "nombre", label: "Nombre" },
      { name: "rif", label: "RIF" },
      { name: "direccion.pais", label: "País", defaultValue: "Venezuela" },
      { name: "direccion.estado", label: "Estado" },
      { name: "direccion.municipio", label: "Municipio" },
      { name: "direccion.sector", label: "Sector" },
      { name: "direccion.descripcion", label: "Dirección" },
      { name: "created_at", label: "Fecha", readOnly: true },
    ],
  },
  granjas: {
    title: "Gestión de Granjas",
    resource: "combined/granjas",
    fields: [
      { name: "ubicacion.nombre", label: "Nombre" },
      { name: "rif", label: "RIF" },
      { name: "ubicacion.tipo", label: "Tipo", defaultValue: "Granja", readOnly: true },
      { name: "ubicacion.direccion.pais", label: "País", defaultValue: "Venezuela" },
      { name: "ubicacion.direccion.estado", label: "Estado" },
      { name: "ubicacion.direccion.municipio", label: "Municipio" },
      { name: "ubicacion.direccion.sector", label: "Sector" },
      { name: "ubicacion.direccion.descripcion", label: "Dirección" },
      { name: "created_at", label: "Fecha", readOnly: true },
    ],
  },
  galpones: {
    title: "Gestión de Galpones",
    resource: "galpones",
    fields: [
      { name: "id_granja", label: "Granja" },
      { name: "nro_galpon", label: "Número de Galpón", type: "number" },
      { name: "capacidad", label: "Capacidad", type: "number" },
      { name: "created_at", label: "Fecha", readOnly: true },
    ],
  },
  vehiculos: {
    title: "Gestión de Vehículos",
    resource: "vehiculos",
    fields: [
      { name: "placa", label: "Placa" },
      { name: "id_empresas_transportes", label: "Empresa Transporte" },
      { name: "created_at", label: "Fecha", readOnly: true },
    ],
  },
  choferes: {
    title: "Gestión de Choferes",
    resource: "combined/choferes",
    fields: [
      { name: "persona.nombre", label: "Nombre" },
      { name: "persona.apellido", label: "Apellido" },
      { name: "persona.cedula", label: "Cédula" },
      { name: "persona.direccion.pais", label: "País", defaultValue: "Venezuela" },
      { name: "persona.direccion.estado", label: "Estado" },
      { name: "persona.direccion.municipio", label: "Municipio" },
      { name: "persona.direccion.sector", label: "Sector" },
      { name: "persona.direccion.descripcion", label: "Dirección" },
      { name: "id_empresas_transportes", label: "Empresa Transporte" },
      { name: "created_at", label: "Fecha", readOnly: true },
    ],
  },
  tickets_pesaje: {
    title: "Tickets de Pesaje",
    resource: "tickets_pesaje",
    fields: [
      { name: "nro_ticket", label: "Nro Ticket" },
      { name: "tipo", label: "Tipo" },
      { name: "id_asignaciones", label: "Asignación" },
      { name: "id_producto", label: "Producto" },
      { name: "id_usuarios_primer_peso", label: "Usuario Primer Peso", readOnly: true },
      {
        name: "peso_bruto",
        label: "Peso Bruto (Kg)",
        type: "number",
        readOnly: true,
      },
      {
        name: "peso_tara",
        label: "Peso Tara (Kg)",
        type: "number",
        readOnly: true,
      },
      {
        name: "peso_neto",
        label: "Peso Neto (Kg)",
        type: "number",
        readOnly: true,
      },
      { name: "id_origen", label: "Origen" },
      { name: "id_destino", label: "Destino" },
      { name: "created_at", label: "Fecha Registro", readOnly: true },
      {
        name: "estado",
        label: "Estado",
        readOnly: true,
        defaultValue: "En proceso",
      },
    ],
  },
};
