"""Migracion Inicial Completasad

Revision ID: 71afc6f22020
Revises: sync_new_schema_2026
Create Date: 2026-02-12 11:43:13.878761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71afc6f22020'
down_revision = 'sync_new_schema_2026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Empresas_direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresas_transportes', sa.Integer(), nullable=False),
    sa.Column('id_direcciones', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_direcciones'], ['Direcciones.id'], name=op.f('fk_Empresas_direcciones_id_direcciones_Direcciones')),
    sa.ForeignKeyConstraint(['id_empresas_transportes'], ['Empresas_transportes.id'], name=op.f('fk_Empresas_direcciones_id_empresas_transportes_Empresas_transportes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Empresas_direcciones'))
    )
    with op.batch_alter_table('Telefonos', schema=None) as batch_op:
        batch_op.create_index('idx_telefonos_numero_unique_active', ['numero'], unique=True, mssql_where=sa.text('is_deleted = 0'))
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ticket_pesaje', schema=None) as batch_op:
        batch_op.alter_column('peso_neto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=11, scale=2),
               existing_nullable=True,
               existing_server_default=sa.Computed('([peso_bruto]-[peso_tara])', persisted=False))

    with op.batch_alter_table('Telefonos', schema=None) as batch_op:
        batch_op.drop_index('idx_telefonos_numero_unique_active', mssql_where=sa.text('is_deleted = 0'))

    op.drop_table('Empresas_direcciones')
    # ### end Alembic commands ###
