"""sync-types

Revision ID: a22391b4de11
Revises: feaa2fc6ba71
Create Date: 2026-01-19 15:16:28.825552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22391b4de11'
down_revision = 'feaa2fc6ba71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Usuarios', 'rol',
               existing_type=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Usuarios', 'rol',
               existing_type=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
