"""creacion inicial de tablas

Revision ID: b1c29528606b
Revises: 
Create Date: 2026-01-30 14:16:20.019711

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash # <--- IMPORTANTE: Agregar esto arriba

# revision identifiers, used by Alembic.
revision = 'b1c29528606b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Empresas_Transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rif', sa.String(length=20), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Empresas_Transporte'))
    )
    op.create_table('Granjas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('dueno', sa.String(length=100), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Granjas'))
    )
    op.create_table('Productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('es_ave_viva', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Productos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_Productos_codigo'))
    )
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Roles')),
    sa.UniqueConstraint('nombre', name=op.f('uq_Roles_nombre'))
    )
    op.create_table('Choferes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('id_empresa_transporte', sa.Integer(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa_transporte'], ['Empresas_Transporte.id'], name=op.f('fk_Choferes_id_empresa_transporte_Empresas_Transporte')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Choferes')),
    sa.UniqueConstraint('cedula', name=op.f('uq_Choferes_cedula'))
    )
    op.create_table('Galpones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_granja', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.ForeignKeyConstraint(['id_granja'], ['Granjas.id'], name=op.f('fk_Galpones_id_granja_Granjas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Galpones'))
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['Roles.id'], name=op.f('fk_Usuarios_id_rol_Roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Usuarios')),
    sa.UniqueConstraint('nombre_usuario', name=op.f('uq_Usuarios_nombre_usuario'))
    )
    op.create_table('Vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('id_empresa_transporte', sa.Integer(), nullable=True),
    sa.Column('peso_tara', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa_transporte'], ['Empresas_Transporte.id'], name=op.f('fk_Vehiculos_id_empresa_transporte_Empresas_Transporte')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Vehiculos')),
    sa.UniqueConstraint('placa', name=op.f('uq_Vehiculos_placa'))
    )
    op.create_table('Tickets_Pesaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_ticket', sa.String(length=50), nullable=False),
    sa.Column('tipo_proceso', sa.String(length=10), nullable=True),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('peso_bruto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('peso_tara', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('peso_neto', sa.Numeric(precision=19, scale=2), sa.Computed('peso_bruto - peso_tara', ), nullable=True),
    sa.Column('peso_avisado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cantidad_cestas', sa.Integer(), server_default='0', nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='Activo', nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.ForeignKeyConstraint(['id_chofer'], ['Choferes.id'], name=op.f('fk_Tickets_Pesaje_id_chofer_Choferes')),
    sa.ForeignKeyConstraint(['id_producto'], ['Productos.id'], name=op.f('fk_Tickets_Pesaje_id_producto_Productos')),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], name=op.f('fk_Tickets_Pesaje_id_usuario_Usuarios')),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['Vehiculos.id'], name=op.f('fk_Tickets_Pesaje_id_vehiculo_Vehiculos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tickets_Pesaje')),
    sa.UniqueConstraint('nro_ticket', name=op.f('uq_Tickets_Pesaje_nro_ticket'))
    )
    op.create_table('Detalles_Transporte_Aves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket_pesaje', sa.Integer(), nullable=False),
    sa.Column('id_granja', sa.Integer(), nullable=False),
    sa.Column('id_galpon', sa.Integer(), nullable=True),
    sa.Column('codigo_lote', sa.String(length=50), nullable=True),
    sa.Column('edad_aves_dias', sa.Integer(), nullable=True),
    sa.Column('hora_salida_granja', mssql.DATETIME2(), nullable=True),
    sa.Column('hora_entrada_romana', mssql.DATETIME2(), nullable=True),
    sa.Column('hora_inicio_proceso', mssql.DATETIME2(), nullable=True),
    sa.Column('hora_fin_proceso', mssql.DATETIME2(), nullable=True),
    sa.Column('aves_transportadas', sa.Integer(), server_default='0', nullable=True),
    sa.Column('aves_contadas', sa.Integer(), server_default='0', nullable=True),
    sa.Column('aves_ahogadas_aho', sa.Integer(), server_default='0', nullable=True),
    sa.Column('aves_por_cesta', sa.Integer(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fecha_registro', mssql.DATETIME2(), server_default=sa.text('getdate()'), nullable=True),
    sa.ForeignKeyConstraint(['id_galpon'], ['Galpones.id'], name=op.f('fk_Detalles_Transporte_Aves_id_galpon_Galpones')),
    sa.ForeignKeyConstraint(['id_granja'], ['Granjas.id'], name=op.f('fk_Detalles_Transporte_Aves_id_granja_Granjas')),
    sa.ForeignKeyConstraint(['id_ticket_pesaje'], ['Tickets_Pesaje.id'], name=op.f('fk_Detalles_Transporte_Aves_id_ticket_pesaje_Tickets_Pesaje')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Detalles_Transporte_Aves')),
    sa.UniqueConstraint('id_ticket_pesaje', name=op.f('uq_Detalles_Transporte_Aves_id_ticket_pesaje'))
    )
    op.drop_table('sysdiagrams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B618A347D13'))
    )
    op.drop_table('Detalles_Transporte_Aves')
    op.drop_table('Tickets_Pesaje')
    op.drop_table('Vehiculos')
    op.drop_table('Usuarios')
    op.drop_table('Galpones')
    op.drop_table('Choferes')
    op.drop_table('Roles')
    op.drop_table('Productos')
    op.drop_table('Granjas')
    op.drop_table('Empresas_Transporte')
    # ### end Alembic commands ###
