"""Migracion Inicial Completa

Revision ID: e3eaa2ef31f4
Revises: 
Create Date: 2026-02-10 14:19:30.214681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3eaa2ef31f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Direcciones'))
    )
    op.create_table('Productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Productos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_Productos_codigo'))
    )
    op.create_table('RIF',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.CheckConstraint("tipo IN ('J', 'G', 'V', 'E')", name=op.f('ck_RIF_ck_rif_tipo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_RIF')),
    sa.UniqueConstraint('numero', name=op.f('uq_RIF_numero'))
    )
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Roles'))
    )
    op.create_table('Telefonos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_pais', sa.String(length=10), nullable=True),
    sa.Column('operadora', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.CheckConstraint("tipo IN ('Celular', 'Casa', 'Trabajo')", name=op.f('ck_Telefonos_ck_telefonos_tipo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Telefonos'))
    )
    op.create_table('Empresas_transportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_direcciones', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_direcciones'], ['Direcciones.id'], name=op.f('fk_Empresas_transportes_id_direcciones_Direcciones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Empresas_transportes'))
    )
    op.create_table('Personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_direcciones', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('tipo_cedula', sa.String(length=1), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.CheckConstraint("tipo_cedula IN ('V', 'E')", name=op.f('ck_Personas_ck_personas_tipo_cedula')),
    sa.ForeignKeyConstraint(['id_direcciones'], ['Direcciones.id'], name=op.f('fk_Personas_id_direcciones_Direcciones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Personas')),
    sa.UniqueConstraint('cedula', name=op.f('uq_Personas_cedula'))
    )
    op.create_table('Ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_direcciones', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.CheckConstraint("tipo IN ('Granja', 'Matadero', 'Balanceados', 'Despresados', 'Incubadora', 'Reciclaje', 'Proveedor', 'Cliente', 'Almacen')", name=op.f('ck_Ubicaciones_ck_ubicaciones_tipo')),
    sa.ForeignKeyConstraint(['id_direcciones'], ['Direcciones.id'], name=op.f('fk_Ubicaciones_id_direcciones_Direcciones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Ubicaciones'))
    )
    op.create_table('Choferes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personas', sa.Integer(), nullable=False),
    sa.Column('id_empresas_transportes', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresas_transportes'], ['Empresas_transportes.id'], name=op.f('fk_Choferes_id_empresas_transportes_Empresas_transportes')),
    sa.ForeignKeyConstraint(['id_personas'], ['Personas.id'], name=op.f('fk_Choferes_id_personas_Personas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Choferes'))
    )
    op.create_table('Empresas_RIF',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresas_transportes', sa.Integer(), nullable=False),
    sa.Column('id_rif', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresas_transportes'], ['Empresas_transportes.id'], name=op.f('fk_Empresas_RIF_id_empresas_transportes_Empresas_transportes')),
    sa.ForeignKeyConstraint(['id_rif'], ['RIF.id'], name=op.f('fk_Empresas_RIF_id_rif_RIF')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Empresas_RIF'))
    )
    with op.batch_alter_table('Empresas_RIF', schema=None) as batch_op:
        batch_op.create_index('idx_empresas_rif_unique_active', ['id_rif'], unique=True, mssql_where=sa.text('is_deleted = 0'))

    op.create_table('Empresas_direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresas_transportes', sa.Integer(), nullable=False),
    sa.Column('id_direcciones', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_direcciones'], ['Direcciones.id'], name=op.f('fk_Empresas_direcciones_id_direcciones_Direcciones')),
    sa.ForeignKeyConstraint(['id_empresas_transportes'], ['Empresas_transportes.id'], name=op.f('fk_Empresas_direcciones_id_empresas_transportes_Empresas_transportes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Empresas_direcciones'))
    )
    op.create_table('Empresas_telefonos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresas_transportes', sa.Integer(), nullable=False),
    sa.Column('id_telefonos', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresas_transportes'], ['Empresas_transportes.id'], name=op.f('fk_Empresas_telefonos_id_empresas_transportes_Empresas_transportes')),
    sa.ForeignKeyConstraint(['id_telefonos'], ['Telefonos.id'], name=op.f('fk_Empresas_telefonos_id_telefonos_Telefonos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Empresas_telefonos'))
    )
    with op.batch_alter_table('Empresas_telefonos', schema=None) as batch_op:
        batch_op.create_index('idx_empresas_telefonos_unique_active', ['id_telefonos'], unique=True, mssql_where=sa.text('is_deleted = 0'))

    op.create_table('Granjas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ubicaciones', sa.Integer(), nullable=False),
    sa.Column('id_persona_responsable', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_persona_responsable'], ['Personas.id'], name=op.f('fk_Granjas_id_persona_responsable_Personas')),
    sa.ForeignKeyConstraint(['id_ubicaciones'], ['Ubicaciones.id'], name=op.f('fk_Granjas_id_ubicaciones_Ubicaciones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Granjas'))
    )
    op.create_table('Personas_direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personas', sa.Integer(), nullable=False),
    sa.Column('id_direcciones', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_direcciones'], ['Direcciones.id'], name=op.f('fk_Personas_direcciones_id_direcciones_Direcciones')),
    sa.ForeignKeyConstraint(['id_personas'], ['Personas.id'], name=op.f('fk_Personas_direcciones_id_personas_Personas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Personas_direcciones'))
    )
    op.create_table('Personas_telefonos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personas', sa.Integer(), nullable=False),
    sa.Column('id_telefonos', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_personas'], ['Personas.id'], name=op.f('fk_Personas_telefonos_id_personas_Personas')),
    sa.ForeignKeyConstraint(['id_telefonos'], ['Telefonos.id'], name=op.f('fk_Personas_telefonos_id_telefonos_Telefonos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Personas_telefonos'))
    )
    with op.batch_alter_table('Personas_telefonos', schema=None) as batch_op:
        batch_op.create_index('idx_personas_telefonos_unique_active', ['id_telefonos'], unique=True, mssql_where=sa.text('is_deleted = 0'))

    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personas', sa.Integer(), nullable=False),
    sa.Column('id_roles', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_personas'], ['Personas.id'], name=op.f('fk_Usuarios_id_personas_Personas')),
    sa.ForeignKeyConstraint(['id_roles'], ['Roles.id'], name=op.f('fk_Usuarios_id_roles_Roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Usuarios')),
    sa.UniqueConstraint('usuario', name=op.f('uq_Usuarios_usuario'))
    )
    op.create_table('Vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('id_empresas_transportes', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresas_transportes'], ['Empresas_transportes.id'], name=op.f('fk_Vehiculos_id_empresas_transportes_Empresas_transportes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Vehiculos')),
    sa.UniqueConstraint('placa', name=op.f('uq_Vehiculos_placa'))
    )
    op.create_table('Asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vehiculos', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_chofer'], ['Choferes.id'], name=op.f('fk_Asignaciones_id_chofer_Choferes')),
    sa.ForeignKeyConstraint(['id_vehiculos'], ['Vehiculos.id'], name=op.f('fk_Asignaciones_id_vehiculos_Vehiculos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Asignaciones'))
    )
    op.create_table('Galpones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_granja', sa.Integer(), nullable=False),
    sa.Column('nro_galpon', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_granja'], ['Granjas.id'], name=op.f('fk_Galpones_id_granja_Granjas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Galpones'))
    )
    op.create_table('Granjas_RIF',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_granjas', sa.Integer(), nullable=False),
    sa.Column('id_rif', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_granjas'], ['Granjas.id'], name=op.f('fk_Granjas_RIF_id_granjas_Granjas')),
    sa.ForeignKeyConstraint(['id_rif'], ['RIF.id'], name=op.f('fk_Granjas_RIF_id_rif_RIF')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Granjas_RIF'))
    )
    with op.batch_alter_table('Granjas_RIF', schema=None) as batch_op:
        batch_op.create_index('idx_granjas_rif_unique_active', ['id_rif'], unique=True, mssql_where=sa.text('is_deleted = 0'))

    op.create_table('Granjas_telefonos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_granjas', sa.Integer(), nullable=False),
    sa.Column('id_telefonos', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_granjas'], ['Granjas.id'], name=op.f('fk_Granjas_telefonos_id_granjas_Granjas')),
    sa.ForeignKeyConstraint(['id_telefonos'], ['Telefonos.id'], name=op.f('fk_Granjas_telefonos_id_telefonos_Telefonos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Granjas_telefonos'))
    )
    with op.batch_alter_table('Granjas_telefonos', schema=None) as batch_op:
        batch_op.create_index('idx_granjas_telefonos_unique_active', ['id_telefonos'], unique=True, mssql_where=sa.text('is_deleted = 0'))

    op.create_table('Lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_galpones', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=50), nullable=False),
    sa.Column('fecha_alojamiento', sa.Date(), nullable=False),
    sa.Column('cantidad_aves', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_galpones'], ['Galpones.id'], name=op.f('fk_Lotes_id_galpones_Galpones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Lotes'))
    )
    op.create_table('Ticket_pesaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_asignaciones', sa.Integer(), nullable=False),
    sa.Column('id_usuarios_primer_peso', sa.Integer(), nullable=False),
    sa.Column('id_usuarios_segundo_peso', sa.Integer(), nullable=True),
    sa.Column('id_origen', sa.Integer(), nullable=False),
    sa.Column('id_destino', sa.Integer(), nullable=False),
    sa.Column('nro_ticket', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('peso_bruto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peso_tara', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('peso_neto', sa.Numeric(precision=10, scale=2), sa.Computed('peso_bruto - peso_tara', ), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=False),
    sa.Column('fecha_primer_peso', sa.DateTime(), nullable=False),
    sa.Column('fecha_segundo_peso', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.CheckConstraint("estado IN ('En proceso', 'Finalizado', 'Anulado')", name=op.f('ck_Ticket_pesaje_ck_ticket_pesaje_estado')),
    sa.CheckConstraint("tipo IN ('Entrada', 'Salida')", name=op.f('ck_Ticket_pesaje_ck_ticket_pesaje_tipo')),
    sa.ForeignKeyConstraint(['id_asignaciones'], ['Asignaciones.id'], name=op.f('fk_Ticket_pesaje_id_asignaciones_Asignaciones')),
    sa.ForeignKeyConstraint(['id_destino'], ['Ubicaciones.id'], name=op.f('fk_Ticket_pesaje_id_destino_Ubicaciones')),
    sa.ForeignKeyConstraint(['id_origen'], ['Ubicaciones.id'], name=op.f('fk_Ticket_pesaje_id_origen_Ubicaciones')),
    sa.ForeignKeyConstraint(['id_producto'], ['Productos.id'], name=op.f('fk_Ticket_pesaje_id_producto_Productos')),
    sa.ForeignKeyConstraint(['id_usuarios_primer_peso'], ['Usuarios.id'], name=op.f('fk_Ticket_pesaje_id_usuarios_primer_peso_Usuarios')),
    sa.ForeignKeyConstraint(['id_usuarios_segundo_peso'], ['Usuarios.id'], name=op.f('fk_Ticket_pesaje_id_usuarios_segundo_peso_Usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Ticket_pesaje')),
    sa.UniqueConstraint('nro_ticket', name=op.f('uq_Ticket_pesaje_nro_ticket'))
    )
    op.create_table('Estadisticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('porcentaje_aves_faltantes', sa.Float(), nullable=True),
    sa.Column('porcentaje_aves_ahogadas', sa.Float(), nullable=True),
    sa.Column('peso_promedio_aves', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['Ticket_pesaje.id'], name=op.f('fk_Estadisticas_id_ticket_Ticket_pesaje')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Estadisticas'))
    )
    op.create_table('Viajes_conteos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('aves_guia', sa.Integer(), nullable=False),
    sa.Column('aves_recibidas', sa.Integer(), nullable=True),
    sa.Column('aves_faltantes', sa.Integer(), sa.Computed('aves_guia - aves_recibidas', ), nullable=True),
    sa.Column('aves_aho', sa.Integer(), nullable=True),
    sa.Column('numero_de_jaulas', sa.Integer(), nullable=False),
    sa.Column('peso_promedio_jaulas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aves_por_jaula', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['Ticket_pesaje.id'], name=op.f('fk_Viajes_conteos_id_ticket_Ticket_pesaje')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Viajes_conteos'))
    )
    op.create_table('Viajes_origen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('numero_de_orden', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['Lotes.id'], name=op.f('fk_Viajes_origen_id_lote_Lotes')),
    sa.ForeignKeyConstraint(['id_ticket'], ['Ticket_pesaje.id'], name=op.f('fk_Viajes_origen_id_ticket_Ticket_pesaje')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Viajes_origen'))
    )
    op.create_table('Viajes_tiempos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('hora_salida_granja', sa.DateTime(), nullable=True),
    sa.Column('hora_llegada_romana', sa.DateTime(), nullable=True),
    sa.Column('hora_inicio_descarga', sa.DateTime(), nullable=True),
    sa.Column('hora_fin_descarga', sa.DateTime(), nullable=True),
    sa.Column('hora_salida_romana', sa.DateTime(), nullable=True),
    sa.Column('tiempo_transito', sa.Integer(), nullable=True),
    sa.Column('tiempo_espera', sa.Integer(), nullable=True),
    sa.Column('tiempo_operacion', sa.Integer(), sa.Computed('DATEDIFF(minute, hora_inicio_descarga, hora_fin_descarga)', ), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['Ticket_pesaje.id'], name=op.f('fk_Viajes_tiempos_id_ticket_Ticket_pesaje')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Viajes_tiempos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Viajes_tiempos')
    op.drop_table('Viajes_origen')
    op.drop_table('Viajes_conteos')
    op.drop_table('Estadisticas')
    op.drop_table('Ticket_pesaje')
    op.drop_table('Lotes')
    with op.batch_alter_table('Granjas_telefonos', schema=None) as batch_op:
        batch_op.drop_index('idx_granjas_telefonos_unique_active', mssql_where=sa.text('is_deleted = 0'))

    op.drop_table('Granjas_telefonos')
    with op.batch_alter_table('Granjas_RIF', schema=None) as batch_op:
        batch_op.drop_index('idx_granjas_rif_unique_active', mssql_where=sa.text('is_deleted = 0'))

    op.drop_table('Granjas_RIF')
    op.drop_table('Galpones')
    op.drop_table('Asignaciones')
    op.drop_table('Vehiculos')
    op.drop_table('Usuarios')
    with op.batch_alter_table('Personas_telefonos', schema=None) as batch_op:
        batch_op.drop_index('idx_personas_telefonos_unique_active', mssql_where=sa.text('is_deleted = 0'))

    op.drop_table('Personas_telefonos')
    op.drop_table('Personas_direcciones')
    op.drop_table('Granjas')
    with op.batch_alter_table('Empresas_telefonos', schema=None) as batch_op:
        batch_op.drop_index('idx_empresas_telefonos_unique_active', mssql_where=sa.text('is_deleted = 0'))

    op.drop_table('Empresas_telefonos')
    op.drop_table('Empresas_direcciones')
    with op.batch_alter_table('Empresas_RIF', schema=None) as batch_op:
        batch_op.drop_index('idx_empresas_rif_unique_active', mssql_where=sa.text('is_deleted = 0'))

    op.drop_table('Empresas_RIF')
    op.drop_table('Choferes')
    op.drop_table('Ubicaciones')
    op.drop_table('Personas')
    op.drop_table('Empresas_transportes')
    op.drop_table('Telefonos')
    op.drop_table('Roles')
    op.drop_table('RIF')
    op.drop_table('Productos')
    op.drop_table('Direcciones')
    # ### end Alembic commands ###
