"""Migracion Inicial Completasad

Revision ID: f79e69b00319
Revises: 7f66ed27afbc
Create Date: 2026-02-18 11:05:11.218433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79e69b00319'
down_revision = '7f66ed27afbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ticket_pesaje', schema=None) as batch_op:
        batch_op.alter_column('peso_bruto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ticket_pesaje', schema=None) as batch_op:
        batch_op.alter_column('peso_bruto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###
