"""init

Revision ID: feaa2fc6ba71
Revises: 
Create Date: 2026-01-19 15:03:29.946974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'feaa2fc6ba71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('Detalles_Transporte_Aves', schema=None) as batch_op:
        batch_op.alter_column('hora_salida_granja',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('hora_entrada_romana',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('hora_inicio_proceso',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('hora_fin_proceso',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('Tickets_Pesaje', schema=None) as batch_op:
        batch_op.alter_column('peso_neto',
               existing_type=sa.DECIMAL(precision=19, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True,
               existing_server_default=sa.Computed('([peso_bruto]-[peso_tara])', persisted=False))
        batch_op.alter_column('fecha_registro',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))

    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               nullable=True)

    with op.batch_alter_table('Tickets_Pesaje', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('peso_neto',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DECIMAL(precision=19, scale=2),
               existing_nullable=True,
               existing_server_default=sa.Computed('([peso_bruto]-[peso_tara])', persisted=False))

    with op.batch_alter_table('Detalles_Transporte_Aves', schema=None) as batch_op:
        batch_op.alter_column('hora_fin_proceso',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
        batch_op.alter_column('hora_inicio_proceso',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
        batch_op.alter_column('hora_entrada_romana',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
        batch_op.alter_column('hora_salida_granja',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6195334766'))
    )
    # ### end Alembic commands ###
